import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export async function generateMetadata(): Promise<Metadata> {
    return {
      title: "Create Next App",
      description: "Generated by create next app",
        other: {
        'fc:miniapp': JSON.stringify({
            version: 'next',
            imageUrl: 'https://notesapp-red-eta.vercel.app/embed-image',
            button: {
                title: `Open App`,
                action: {
                    type: 'launch_miniapp',
                    name: 'Notes App',
                    url: 'https://notesapp-red-eta.vercel.app',
                    splashImageUrl: 'https://notesapp-red-eta.vercel.app/image.jpeg',
                    splashBackgroundColor: '#000000',
                },
            },
        }),
        },
    };
    }

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        {children}
      </body>
    </html>
  );
}
